package models

type Record struct {
	ID                            int     `db:"id" json:"id"`
	PartnerID                     string  `db:"partner_id" json:"partner_id"`
	PartnerName                   string  `db:"partner_name" json:"partner_name"`
	CustomerID                    string  `db:"customer_id" json:"customer_id"`
	CustomerName                  string  `db:"customer_name" json:"customer_name"`
	CustomerDomainName            string  `db:"customer_domain_name" json:"customer_domain_name"`
	CustomerCountry               string  `db:"customer_country" json:"customer_country"`
	MpnID                         string  `db:"mpn_id" json:"mpn_id"`
	Tier2MpnID                    string  `db:"tier2_mpn_id" json:"tier2_mpn_id"`
	InvoiceNumber                 string  `db:"invoice_number" json:"invoice_number"`
	ProductID                     string  `db:"product_id" json:"product_id"`
	SkuID                         string  `db:"sku_id" json:"sku_id"`
	AvailabilityID                string  `db:"availability_id" json:"availability_id"`
	SkuName                       string  `db:"sku_name" json:"sku_name"`
	ProductName                   string  `db:"product_name" json:"product_name"`
	PublisherName                 string  `db:"publisher_name" json:"publisher_name"`
	PublisherID                   string  `db:"publisher_id" json:"publisher_id"`
	SubscriptionDescription       string  `db:"subscription_description" json:"subscription_description"`
	SubscriptionID                string  `db:"subscription_id" json:"subscription_id"`
	ChargeStartDate               string  `db:"charge_start_date" json:"charge_start_date"`
	ChargeEndDate                 string  `db:"charge_end_date" json:"charge_end_date"`
	UsageDate                     string  `db:"usage_date" json:"usage_date"`
	MeterType                     string  `db:"meter_type" json:"meter_type"`
	MeterCategory                 string  `db:"meter_category" json:"meter_category"`
	MeterID                       string  `db:"meter_id" json:"meter_id"`
	MeterSubCategory              string  `db:"meter_sub_category" json:"meter_sub_category"`
	MeterName                     string  `db:"meter_name" json:"meter_name"`
	MeterRegion                   string  `db:"meter_region" json:"meter_region"`
	Unit                          string  `db:"unit" json:"unit"`
	ResourceLocation              string  `db:"resource_location" json:"resource_location"`
	ConsumedService               string  `db:"consumed_service" json:"consumed_service"`
	ResourceGroup                 string  `db:"resource_group" json:"resource_group"`
	ResourceURI                   string  `db:"resource_uri" json:"resource_uri"`
	ChargeType                    string  `db:"charge_type" json:"charge_type"`
	UnitPrice                     float64 `db:"unit_price" json:"unit_price"`
	Quantity                      float64 `db:"quantity" json:"quantity"`
	UnitType                      string  `db:"unit_type" json:"unit_type"`
	BillingPreTaxTotal            float64 `db:"billing_pre_tax_total" json:"billing_pre_tax_total"`
	BillingCurrency               string  `db:"billing_currency" json:"billing_currency"`
	PricingPreTaxTotal            float64 `db:"pricing_pre_tax_total" json:"pricing_pre_tax_total"`
	PricingCurrency               string  `db:"pricing_currency" json:"pricing_currency"`
	ServiceInfo1                  string  `db:"service_info1" json:"service_info1"`
	ServiceInfo2                  string  `db:"service_info2" json:"service_info2"`
	Tags                          string  `db:"tags" json:"tags"`
	AdditionalInfo                string  `db:"additional_info" json:"additional_info"`
	EffectiveUnitPrice            float64 `db:"effective_unit_price" json:"effective_unit_price"`
	PctToBCExchangeRate           float64 `db:"pct_to_bc_exchange_rate" json:"pct_to_bc_exchange_rate"`
	PctToBCExchangeRateDate       string  `db:"pct_to_bc_exchange_rate_date" json:"pct_to_bc_exchange_rate_date"`
	EntitlementID                 string  `db:"entitlement_id" json:"entitlement_id"`
	EntitlementDescription        string  `db:"entitlement_description" json:"entitlement_description"`
	PartnerEarnedCreditPercentage float64 `db:"partner_earned_credit_percentage" json:"partner_earned_credit_percentage"`
	CreditPercentage              float64 `db:"credit_percentage" json:"credit_percentage"`
	CreditType                    string  `db:"credit_type" json:"credit_type"`
	BenefitOrderID                string  `db:"benefit_order_id" json:"benefit_order_id"`
	BenefitID                     string  `db:"benefit_id" json:"benefit_id"`
	BenefitType                   string  `db:"benefit_type" json:"benefit_type"`
}
